apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-mainfest.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "k8s-mainfest.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
